module.exports = {
  RECIEVE_RETAILERS: 'RECIEVE_RETAILERS',
  RECIEVE_RETAILER: 'RECIEVE_RETAILER',
  RECIEVE_RETAILER_ERROR: 'RECIEVE_RETAILER_ERROR',
  RECIEVE_RETAILERs_ERROR: 'RECIEVE_RETAILERs_ERROR'
}